spring.application.name=placement-management-api

# ❌ REMOVE Docker DB config
# spring.datasource.url=jdbc:mysql://db:3306/placement_db
# spring.datasource.username=root
# spring.datasource.password=root

# ✅ TEMP: disable DB so app can start
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:5000}